/*
 * Adc_Cfg.h
 *
 *  Created on: Feb 19, 2021
 *      Author: Muhammad.Elzeiny
 */

#ifndef AMITLATTE_USERCONFIG_ADC_CFG_H_
#define AMITLATTE_USERCONFIG_ADC_CFG_H_

#define ADC_AUTO_TRIGGER_EN         DISABLE  /*disable if Single conversion needed*/
#define ADC_INTERRUPT_EN            DISABLE

/*
 * Please choose from the followings
 * ADC_PRESCALER_2  0x01
 * ADC_PRESCALER_4  0x02
 * ADC_PRESCALER_8  0x03
 * ADC_PRESCALER_16 0x04
 * ADC_PRESCALER_32 0x05
 * ADC_PRESCALER_64 0x06
 * ADC_PRESCALER_128 0x07
 *
 * */
#define ADC_PRESCALER_SELECTOR    ADC_PRESCALER_16

/*
 * ADC_VREF_SOURCE_AREF     0x00
 * ADC_VREF_SOURCE_AVCC     0x01
 * ADC_VREF_SOURCE_2_56     0x03
 * */
#define ADC_VREF_SOURCE_SELECTOR   ADC_VREF_SOURCE_AVCC
/*
 * ADC_RESOLUTION_8      0x1
 * ADC_RESOLUTION_10     0x0
 * */
#define ADC_RESOLUTION_SELECTOR   ADC_RESOLUTION_10

/*
 * ADC_TRIGGER_SOURCE_FREE_RUNNING
 * ADC_TRIGGER_SOURCE_ANCOMPARATOR
 * ADC_TRIGGER_SOURCE_EXT0
 * ADC_TRIGGER_SOURCE_TIM0COMP
 * ADC_TRIGGER_SOURCE_TIM0OVF
 * ADC_TRIGGER_SOURCE_TIM1COMPB
 * ADC_TRIGGER_SOURCE_TIM1OVF
 * ADC_TRIGGER_SOURCE_TIM1CP
 * */
#define ADC_TRIGGER_SOURCE_SELECTOR    ADC_TRIGGER_SOURCE_FREE_RUNNING

#define ADC_VREF_mV                    5000
#endif /* AMITLATTE_USERCONFIG_ADC_CFG_H_ */
