/*
 * Spi_Cfg.h
 *
 *  Created on: Feb 26, 2021
 *      Author: Muhammad.Elzeiny
 */

#ifndef AMITLATTE_USERCONFIG_SPI_CFG_H_
#define AMITLATTE_USERCONFIG_SPI_CFG_H_

#define SPI_INTERRUPT_EN				DISABLE
/*
 * SPI_DATA_ORDER_LSB
 * SPI_DATA_ORDER_MSB
 * */
#define SPI_DATA_ORDER_SELECTOR        SPI_DATA_ORDER_LSB
/*
 * SPI_MODE_SLAVE
 * SPI_MODE_MASTER*/
#define SPI_MODE_SELECTOR              SPI_MODE_MASTER
/*
 * SPI_LEADING_EDGE_RISING  : Low When Idle
 * SPI_LEADING_EDGE_FALLING : High When Idle
 * */
#define SPI_CLOCK_POLARITY_SELECTOR   SPI_LEADING_EDGE_RISING
/*
 * SPI_SAMPLE_ON_LEADING
 * SPI_SETUP_ON_LEADING
 * */
#define SPI_CLOCK_PHASE_SELECTOR   	  SPI_SETUP_ON_LEADING
/*
 * SPI_PRESCALER_4
 * SPI_PRESCALER_16
 * SPI_PRESCALER_64
 * SPI_PRESCALER_128
 * */
#define SPI_PRESCALER_SELECTOR        SPI_PRESCALER_16

#define SPI_MAX_RX_BUFFER_SIZE        100

#endif /* AMITLATTE_USERCONFIG_SPI_CFG_H_ */
